# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    # Test name: اشخاص و شرکتها تست کد ملی نامتبر
    # Step # | name | target | value
    # 1 | open | /fa | 
    self.driver.get("https://frontbuildstage.ariansystemdp.local/fa")
    # 2 | setWindowSize | 1456x876 | 
    self.driver.set_window_size(1456, 876)
    # 3 | click | id=Login_username | 
    self.driver.find_element(By.ID, "Login_username").click()
    # 4 | type | id=Login_username | 12
    self.driver.find_element(By.ID, "Login_username").send_keys("12")
    # 5 | click | css=.ant-input-affix-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-affix-wrapper").click()
    # 6 | type | id=Login_password | 12
    self.driver.find_element(By.ID, "Login_password").send_keys("12")
    # 7 | click | css=.ant-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn").click()
    # 8 | click | css=.ant-menu-title-content | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-title-content").click()
    # 9 | click | css=.ant-menu-submenu-active > .ant-menu-submenu-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-submenu-active > .ant-menu-submenu-title").click()
    # 10 | click | css=.ant-menu-item:nth-child(1) > .ant-menu-title-content span | 
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-item:nth-child(1) > .ant-menu-title-content span").click()
    # 11 | mouseOver | css=.ant-collapse:nth-child(3) .ant-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".ant-collapse:nth-child(3) .ant-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | css=.bg-black-black8 > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span").click()
    # 13 | mouseOver | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | id=DisplayName | 
    self.driver.find_element(By.ID, "DisplayName").click()
    # 16 | type | id=DisplayName | نیکانی
    self.driver.find_element(By.ID, "DisplayName").send_keys("نیکانی")
    # 17 | click | id=FirstName | 
    self.driver.find_element(By.ID, "FirstName").click()
    # 18 | type | id=FirstName | نیکان
    self.driver.find_element(By.ID, "FirstName").send_keys("نیکان")
    # 19 | click | id=LastName | 
    self.driver.find_element(By.ID, "LastName").click()
    # 20 | type | id=LastName | ریاحی
    self.driver.find_element(By.ID, "LastName").send_keys("ریاحی")
    # 21 | click | id=NationalCode | 
    self.driver.find_element(By.ID, "NationalCode").click()
    # 22 | type | id=NationalCode | 0080018342
    self.driver.find_element(By.ID, "NationalCode").send_keys("0080018342")
    # 23 | click | id=EconomicCode | 
    self.driver.find_element(By.ID, "EconomicCode").click()
    # 24 | type | id=EconomicCode | 123654789654
    self.driver.find_element(By.ID, "EconomicCode").send_keys("123654789654")
    # 25 | click | css=.bg-black-black8 > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span").click()
    # 26 | mouseOver | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 27 | mouseOut | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 28 | click | id=NationalCode | 
    self.driver.find_element(By.ID, "NationalCode").click()
    # 29 | type | id=NationalCode | 0080018343
    self.driver.find_element(By.ID, "NationalCode").send_keys("0080018343")
    # 30 | click | css=.bg-black-black8 > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span").click()
    # 31 | mouseOver | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-black-black8 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 32 | mouseOut | css=.bg-black-black8 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 33 | click | css=.Toastify__close-button path | 
    self.driver.find_element(By.CSS_SELECTOR, ".Toastify__close-button path").click()
    # 34 | click | css=.text-main-black > .ant-btn-sm > svg | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-main-black > .ant-btn-sm > svg").click()
    # 35 | click | css=.hover\3A bg-white | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-white").click()
    # 36 | click | css=.bg-gray-gray3:nth-child(2) > svg | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-gray3:nth-child(2) > svg").click()
  
